### ISSUE TITLE
Proposal: Require squash commits for osquery

### ISSUE THREAD

**Issue by directionless** [osquery/foundation#5]
I propose we require squash commits for osquery. 

My interest comes from working in large monorepos, and allowing people to iterate with a lot of little commits. These days, github has a toggles. We currently allow rebase and squash. I propose we only allow squash.

Please vote, thumbs up or thumbs down. Or discuss if there's something substantial

**Comment by alessandrogario** [comment]
I think it depends on each PR, and the option should be left available. It is sometimes really good to keep the commits if they are atomic and well formed (and also helps quite a lot when bisecting or rebasing).

**Comment by groob** [comment]
I think the github configuration for pull requests should default to squash commit. 
I also think we need the ability for a maintainer to do a rebase/merge and push to master when necessary, because not every thing will fit into the squash & merge model. 

But lots of small changes creates as a pull request fit the squash model well. 

I'd biased against rebase as a github UI feature because it works a little bit differently and unlike squash is high friction. https://help.github.com/en/articles/about-pull-request-merges#rebase-and-merge-your-pull-request-commits

**Comment by groob** [comment]
<img width="765" alt="Screen Shot 2019-06-26 at 11 48 27 PM" src="https://user-images.githubusercontent.com/1526945/60233102-fa048180-986c-11e9-9ece-effeb90076cd.png">

The current options look like this, where merge is blocked, but the other two options are allowed. 
I see no reason to restrict it further, until such a need comes up. 

So I change my vote to "keep as it is right now".

**Comment by theopolis** [comment]
Yes, sometimes I take someone else’s commit and open a PR with it. If I squash merge it then GitHub removes their contact/authorship details.

**Comment by directionless** [comment]
@theopolis One workaround there is to use https://help.github.com/en/articles/creating-a-commit-with-multiple-authors. Stick `Co-authored-by: name <name@example.com>` into the body.

So far, this seems evenly split. I'm not going to change anything, but I'll leave this open for comment a little longer

**Comment by directionless** [comment]
This has been open for 7-14 days, and there's broad disagreement. Closing!
